version: "3"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    networks: 
      - app_network
    env_file: .env

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./src/apps/backend/api/Dockerfile
    restart: always
    ports: 
      - 3001:3001
    networks: 
      - app_network
    depends_on: 
      - database
    env_file: .env

  mechanic:
    container_name: mechanic
    build: 
      context: .
      dockerfile: ./src/apps/frontend/mechanic/Dockerfile
    restart: always
    ports: 
      - 3000:3000
    networks: 
      - app_network
    depends_on: 
      - api
    env_file: .env

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true